import {
  ExecutionRunLockError,
  hasExecutionRunEvent,
  loadExecutionRunRecord,
  markExecutionRunEventApplied,
  type ExecutionRunStatus,
  type ExecutionRunRecord,
  withExecutionRunLock,
} from './run-store';
import { applyHermesMarketingCallback } from '../marketing/hermes-callbacks';
import { SOCIAL_CONTENT_WEEKLY_WORKFLOW_KEY } from '../social-content/defaults';
import { approvalStepFromWorkflowStepId } from '../social-content/runtime-state';

export type HermesRunCallbackStatus =
  | 'running'
  | 'requires_approval'
  | 'completed'
  | 'failed'
  | 'cancelled';

export type HermesRunCallbackPayload = {
  event_id: string;
  aries_run_id: string;
  hermes_run_id?: string;
  status: HermesRunCallbackStatus;
  stage?:
    | 'intake'
    | 'research'
    | 'planning'
    | 'plan_review'
    | 'copy_production'
    | 'image_briefing'
    | 'image_creatives'
    | 'image_generation'
    | 'creative_review'
    | 'video_script'
    | 'video_review'
    | 'video_render'
    | 'publish_review'
    | 'completed'
    | 'failed'
    | 'production'
    | 'approval'
    | 'publish'
    | 'strategy';
  output?: Record<string, unknown> | Record<string, unknown>[];
  artifacts?: unknown[];
  approval?: {
    stage: 'plan' | 'creative' | 'video' | 'publish' | 'strategy' | 'production';
    approval_step?:
      | 'approve_weekly_plan'
      | 'approve_post_copy'
      | 'approve_image_creatives'
      | 'approve_video_script'
      | 'approve_video_render'
      | 'approve_publish';
    workflow_step_id: string;
    prompt: string;
    resume_token?: string;
  };
  error?: { code?: string; message: string; retryable?: boolean };
};

export type HermesRunCallbackResult =
  | { status: 'accepted'; ariesRunId: string; duplicate: boolean }
  | { status: 'error'; reason: string };

type HermesRunApproval = NonNullable<HermesRunCallbackPayload['approval']>;

function sanitizeApprovalForRunRecord(approval: HermesRunApproval): Record<string, unknown> {
  return {
    stage: approval.stage,
    approval_step: approval.approval_step ?? null,
    workflow_step_id: approval.workflow_step_id,
    prompt: approval.prompt,
    has_resume_token: typeof approval.resume_token === 'string' && approval.resume_token.trim().length > 0,
  };
}

function recordValue(value: unknown): Record<string, unknown> | null {
  return value && typeof value === 'object' && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : null;
}

function stringValue(value: unknown): string {
  return typeof value === 'string' ? value.trim() : '';
}

// Matches the format generated by createExecutionRunRecord: arun_<uuid>
const ARIES_RUN_ID_RE = /^arun_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

function isValidAriesRunId(value: string): boolean {
  return ARIES_RUN_ID_RE.test(value);
}

function isCallbackStatus(value: string): value is HermesRunCallbackStatus {
  return value === 'running'
    || value === 'requires_approval'
    || value === 'completed'
    || value === 'failed'
    || value === 'cancelled';
}

function isApprovalStage(value: string): value is HermesRunApproval['stage'] {
  return value === 'plan'
    || value === 'creative'
    || value === 'video'
    || value === 'publish'
    || value === 'strategy'
    || value === 'production';
}

function isCallbackStage(
  value: string,
): value is NonNullable<HermesRunCallbackPayload['stage']> {
  return value === 'intake'
    || value === 'research'
    || value === 'planning'
    || value === 'plan_review'
    || value === 'copy_production'
    || value === 'image_briefing'
    || value === 'image_creatives'
    || value === 'image_generation'
    || value === 'creative_review'
    || value === 'video_script'
    || value === 'video_review'
    || value === 'video_render'
    || value === 'publish_review'
    || value === 'completed'
    || value === 'failed'
    || value === 'production'
    || value === 'approval'
    || value === 'publish'
    || value === 'strategy';
}

function parseApproval(value: unknown): HermesRunCallbackPayload['approval'] | undefined {
  const record = recordValue(value);
  if (!record) {
    return undefined;
  }
  const stage = stringValue(record.stage);
  const workflowStepId = stringValue(record.workflow_step_id);
  const prompt = stringValue(record.prompt);
  const resumeToken = stringValue(record.resume_token);
  const explicitApprovalStep = stringValue(record.approval_step || record.approvalStep);
  const approvalStep = (
    explicitApprovalStep === 'approve_weekly_plan'
    || explicitApprovalStep === 'approve_post_copy'
    || explicitApprovalStep === 'approve_image_creatives'
    || explicitApprovalStep === 'approve_video_script'
    || explicitApprovalStep === 'approve_video_render'
    || explicitApprovalStep === 'approve_publish'
  )
    ? explicitApprovalStep
    : approvalStepFromWorkflowStepId(workflowStepId);
  if (
    !workflowStepId
    || !prompt
    || (!isApprovalStage(stage) && !approvalStep)
  ) {
    return undefined;
  }
  const normalizedStage = isApprovalStage(stage)
    ? stage
    : approvalStep === 'approve_weekly_plan'
      ? 'strategy'
      : approvalStep === 'approve_publish'
        ? 'publish'
        : 'production';
  return {
    stage: normalizedStage,
    approval_step: approvalStep ?? undefined,
    workflow_step_id: workflowStepId,
    prompt,
    resume_token: resumeToken || undefined,
  };
}

function parseCallbackError(value: unknown): HermesRunCallbackPayload['error'] | undefined {
  const record = recordValue(value);
  if (!record) {
    return undefined;
  }
  const message = stringValue(record.message);
  if (!message) {
    return undefined;
  }
  const code = stringValue(record.code);
  return {
    code: code || undefined,
    message,
    retryable: typeof record.retryable === 'boolean' ? record.retryable : undefined,
  };
}

function executionStatus(status: HermesRunCallbackStatus): ExecutionRunStatus {
  return status === 'requires_approval' ? 'awaiting_approval' : status;
}

export function parseHermesRunCallbackPayload(value: unknown): HermesRunCallbackPayload | null {
  const record = recordValue(value);
  if (!record) {
    return null;
  }
  const eventId = stringValue(record.event_id);
  const ariesRunId = stringValue(record.aries_run_id);
  const status = stringValue(record.status);
  const stage = stringValue(record.stage);
  if (!eventId || !ariesRunId || !isCallbackStatus(status) || !isValidAriesRunId(ariesRunId)) {
    return null;
  }

  return {
    event_id: eventId,
    aries_run_id: ariesRunId,
    hermes_run_id: stringValue(record.hermes_run_id) || undefined,
    status,
    stage: isCallbackStage(stage) ? stage : undefined,
    output: Array.isArray(record.output) || recordValue(record.output)
      ? (record.output as HermesRunCallbackPayload['output'])
      : undefined,
    artifacts: Array.isArray(record.artifacts) ? record.artifacts : undefined,
    approval: parseApproval(record.approval),
    error: parseCallbackError(record.error),
  };
}

function validateRunCorrelation(
  run: ExecutionRunRecord,
  payload: HermesRunCallbackPayload,
): HermesRunCallbackResult | null {
  if (!run.external_run_id) {
    return null;
  }
  if (!payload.hermes_run_id) {
    return { status: 'error', reason: 'missing_hermes_run_id' };
  }
  if (payload.hermes_run_id !== run.external_run_id) {
    return { status: 'error', reason: 'hermes_run_id_mismatch' };
  }
  return null;
}

function validateApprovalTransition(
  run: ExecutionRunRecord,
  payload: HermesRunCallbackPayload,
): HermesRunCallbackResult | null {
  if (payload.status !== 'requires_approval') {
    return null;
  }
  if (!payload.approval) {
    return { status: 'error', reason: 'missing_approval_payload' };
  }
  if (run.domain !== 'marketing') {
    return { status: 'error', reason: 'approval_not_supported_for_domain' };
  }
  if (run.workflow_key === SOCIAL_CONTENT_WEEKLY_WORKFLOW_KEY) {
    const approvalStep = payload.approval.approval_step
      ?? approvalStepFromWorkflowStepId(payload.approval.workflow_step_id);
    if (!approvalStep) {
      return { status: 'error', reason: 'approval_stage_mismatch' };
    }
    // Video render/script approvals occur during the production run stage but
    // gate the publish gate — they map to 'publish' in the allowlist, not
    // 'production', so the stage check passes correctly.
    const expectedMarketingStage = approvalStep === 'approve_weekly_plan'
      ? 'strategy'
      : (approvalStep === 'approve_publish'
        || approvalStep === 'approve_video_render'
        || approvalStep === 'approve_video_script')
        ? 'publish'
        : 'production';
    // Explicit per-stage allowlist: each run stage maps to exactly one valid
    // approval stage. Anything else — skip forward, regression, or unknown stage
    // — is rejected so the caller fails loud instead of silently misrouting.
    const SOCIAL_CONTENT_ALLOWED_APPROVAL: Record<string, string> = {
      research: 'strategy',
      strategy: 'production',
      production: 'publish',
      publish: 'publish',
    };
    if (SOCIAL_CONTENT_ALLOWED_APPROVAL[run.stage ?? ''] !== expectedMarketingStage) {
      return { status: 'error', reason: 'approval_stage_mismatch' };
    }
    return null;
  }
  if (
    run.stage === 'research'
    && payload.approval.stage !== 'strategy'
    && payload.approval.stage !== 'plan'
  ) {
    return { status: 'error', reason: 'approval_stage_mismatch' };
  }
  if (
    run.stage === 'strategy'
    && payload.approval.stage !== 'production'
    && payload.approval.stage !== 'creative'
    && payload.approval.stage !== 'video'
  ) {
    return { status: 'error', reason: 'approval_stage_mismatch' };
  }
  if (run.stage === 'production' && payload.approval.stage !== 'publish') {
    return { status: 'error', reason: 'approval_stage_mismatch' };
  }
  return null;
}

export async function handleHermesRunCallback(
  payload: HermesRunCallbackPayload,
): Promise<HermesRunCallbackResult> {
  try {
    return await withExecutionRunLock(payload.aries_run_id, async () => {
      const run = loadExecutionRunRecord(payload.aries_run_id);
      if (!run) {
        return { status: 'error', reason: 'execution_run_not_found' };
      }

      if (hasExecutionRunEvent(payload.aries_run_id, payload.event_id)) {
        return {
          status: 'accepted',
          ariesRunId: payload.aries_run_id,
          duplicate: true,
        };
      }

      const correlationError = validateRunCorrelation(run, payload);
      if (correlationError) {
        return correlationError;
      }

      const approvalError = validateApprovalTransition(run, payload);
      if (approvalError) {
        return approvalError;
      }

      if (run.domain === 'marketing') {
        await applyHermesMarketingCallback(run, payload);
      }

      markExecutionRunEventApplied(payload.aries_run_id, {
        eventId: payload.event_id,
        status: executionStatus(payload.status),
        stage: payload.stage,
        result: payload.output ?? (payload.approval ? sanitizeApprovalForRunRecord(payload.approval) : null),
        externalRunId: payload.hermes_run_id,
        error: payload.error
          ? {
              code: payload.error.code ?? 'hermes_callback_error',
              message: payload.error.message,
              retryable: payload.error.retryable,
            }
          : null,
      });

      return {
        status: 'accepted',
        ariesRunId: payload.aries_run_id,
        duplicate: false,
      };
    });
  } catch (error) {
    if (error instanceof ExecutionRunLockError) {
      return { status: 'error', reason: 'execution_run_locked' };
    }
    throw error;
  }
}
