import {
  ExecutionRunLockError,
  hasExecutionRunEvent,
  isTerminalExecutionStatus,
  loadExecutionRunRecord,
  markExecutionRunEventApplied,
  type ExecutionRunStatus,
  type ExecutionRunRecord,
  withExecutionRunLock,
} from './run-store';
import { estimateAiCostCents } from '../telemetry/task-execution-log';
import { applyHermesMarketingCallback } from '../marketing/hermes-callbacks';
import { loadSocialContentJobRuntime } from '../marketing/runtime-state';
import { SOCIAL_CONTENT_WEEKLY_WORKFLOW_KEY } from '../social-content/defaults';
import { approvalStepFromWorkflowStepId } from '../social-content/runtime-state';
import {
  HermesRunCallbackPayloadSchema,
  isCompatibleProtocolVersion,
} from '@aries/hermes-protocol';
import type {
  HermesRunCallbackPayload,
  HermesRunCallbackStatus,
} from '@aries/hermes-protocol';

// Re-export so existing callers that import these from this module continue to work.
export type { HermesRunCallbackPayload, HermesRunCallbackStatus };

export type HermesRunCallbackResult =
  | { status: 'accepted'; ariesRunId: string; duplicate: boolean }
  | { status: 'error'; reason: string };

type HermesRunApproval = NonNullable<HermesRunCallbackPayload['approval']>;

function sanitizeApprovalForRunRecord(approval: HermesRunApproval): Record<string, unknown> {
  return {
    stage: approval.stage,
    approval_step: approval.approval_step ?? null,
    workflow_step_id: approval.workflow_step_id,
    prompt: approval.prompt,
    has_resume_token: typeof approval.resume_token === 'string' && approval.resume_token.trim().length > 0,
  };
}

// Matches the format generated by createExecutionRunRecord: arun_<uuid>
const ARIES_RUN_ID_RE = /^arun_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

function isValidAriesRunId(value: string): boolean {
  return ARIES_RUN_ID_RE.test(value);
}


function executionStatus(status: HermesRunCallbackStatus): ExecutionRunStatus {
  if (status === 'requires_approval') return 'awaiting_approval';
  // 'stopped' is Hermes' alternate terminal cancellation status; map to 'cancelled'
  // which is the canonical internal terminal for that outcome.
  if (status === 'stopped') return 'cancelled';
  return status;
}

/**
 * Pre-processes the raw incoming approval object to fill in missing fields
 * before Zod validation. Specifically:
 *  - Infers `approval_step` from `workflow_step_id` when the field is absent.
 *  - Normalizes `stage` from approval_step when `stage` is absent or unknown.
 * These normalizations happen at the inbound wire boundary, keeping the Zod
 * schema strict about what it accepts internally.
 */
function preprocessApproval(raw: unknown): unknown {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return raw;
  const record = raw as Record<string, unknown>;

  const workflowStepId = typeof record.workflow_step_id === 'string' ? record.workflow_step_id.trim() : '';
  const explicitStep = typeof record.approval_step === 'string' ? record.approval_step.trim()
    : typeof record.approvalStep === 'string' ? record.approvalStep.trim() : '';

  const inferredStep = explicitStep || approvalStepFromWorkflowStepId(workflowStepId) || '';

  const currentStage = typeof record.stage === 'string' ? record.stage.trim() : '';
  const VALID_APPROVAL_STAGES = new Set(['plan', 'creative', 'video', 'publish', 'strategy', 'production']);
  const normalizedStage = VALID_APPROVAL_STAGES.has(currentStage)
    ? currentStage
    : inferredStep === 'approve_weekly_plan'
      ? 'strategy'
      : inferredStep === 'approve_publish'
        ? 'publish'
        : inferredStep
          ? 'production'
          : currentStage;

  return {
    ...record,
    approval_step: inferredStep || record.approval_step,
    stage: normalizedStage || record.stage,
  };
}

export function parseHermesRunCallbackPayload(value: unknown): HermesRunCallbackPayload | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null;
  const raw = value as Record<string, unknown>;

  // Structural pre-check: aries_run_id format must be valid before Zod parsing
  // to avoid leaking internal run IDs in error messages.
  const ariesRunId = typeof raw.aries_run_id === 'string' ? raw.aries_run_id.trim() : '';
  if (!ariesRunId || !isValidAriesRunId(ariesRunId)) return null;

  // Protocol version compatibility check: reject major-version mismatches loud.
  const incomingVersion = typeof raw.protocol_version === 'string' ? raw.protocol_version.trim() : null;
  if (incomingVersion && !isCompatibleProtocolVersion(incomingVersion)) {
    console.warn('[hermes-callbacks] protocol_version_mismatch', {
      incoming: incomingVersion,
      aries_run_id: ariesRunId,
    });
    return null;
  }

  // Pre-process the approval envelope before schema validation.
  const preprocessed = {
    ...raw,
    approval: raw.approval != null ? preprocessApproval(raw.approval) : raw.approval,
  };

  const result = HermesRunCallbackPayloadSchema.safeParse(preprocessed);
  if (!result.success) {
    return null;
  }
  return result.data;
}

function validateRunCorrelation(
  run: ExecutionRunRecord,
  payload: HermesRunCallbackPayload,
): HermesRunCallbackResult | null {
  if (!run.external_run_id) {
    return null;
  }
  if (!payload.hermes_run_id) {
    return { status: 'error', reason: 'missing_hermes_run_id' };
  }
  if (payload.hermes_run_id !== run.external_run_id) {
    return { status: 'error', reason: 'hermes_run_id_mismatch' };
  }
  return null;
}

function validateApprovalTransition(
  run: ExecutionRunRecord,
  payload: HermesRunCallbackPayload,
): HermesRunCallbackResult | null {
  if (payload.status !== 'requires_approval') {
    return null;
  }
  if (!payload.approval) {
    return { status: 'error', reason: 'missing_approval_payload' };
  }
  if (run.domain !== 'marketing') {
    return { status: 'error', reason: 'approval_not_supported_for_domain' };
  }
  if (run.workflow_key === SOCIAL_CONTENT_WEEKLY_WORKFLOW_KEY) {
    const approvalStep = payload.approval.approval_step
      ?? approvalStepFromWorkflowStepId(payload.approval.workflow_step_id);
    if (!approvalStep) {
      return { status: 'error', reason: 'approval_stage_mismatch' };
    }
    // Video render/script approvals occur during the production run stage but
    // gate the publish gate — they map to 'publish' in the allowlist, not
    // 'production', so the stage check passes correctly.
    const expectedMarketingStage = approvalStep === 'approve_weekly_plan'
      ? 'strategy'
      : (approvalStep === 'approve_publish'
        || approvalStep === 'approve_video_render'
        || approvalStep === 'approve_video_script')
        ? 'publish'
        : 'production';
    // Explicit per-stage allowlist: each run stage maps to exactly one valid
    // approval stage. Anything else — skip forward, regression, or unknown stage
    // — is rejected so the caller fails loud instead of silently misrouting.
    const SOCIAL_CONTENT_ALLOWED_APPROVAL: Record<string, string> = {
      research: 'strategy',
      strategy: 'production',
      production: 'publish',
      publish: 'publish',
    };
    if (SOCIAL_CONTENT_ALLOWED_APPROVAL[run.stage ?? ''] !== expectedMarketingStage) {
      return { status: 'error', reason: 'approval_stage_mismatch' };
    }
    return null;
  }
  if (
    run.stage === 'research'
    && payload.approval.stage !== 'strategy'
    && payload.approval.stage !== 'plan'
  ) {
    return { status: 'error', reason: 'approval_stage_mismatch' };
  }
  if (
    run.stage === 'strategy'
    && payload.approval.stage !== 'production'
    && payload.approval.stage !== 'creative'
    && payload.approval.stage !== 'video'
  ) {
    return { status: 'error', reason: 'approval_stage_mismatch' };
  }
  if (run.stage === 'production' && payload.approval.stage !== 'publish') {
    return { status: 'error', reason: 'approval_stage_mismatch' };
  }
  return null;
}

export async function handleHermesRunCallback(
  payload: HermesRunCallbackPayload,
): Promise<HermesRunCallbackResult> {
  try {
    return await withExecutionRunLock(payload.aries_run_id, async () => {
      const run = loadExecutionRunRecord(payload.aries_run_id);
      if (!run) {
        return { status: 'error', reason: 'execution_run_not_found' };
      }

      if (hasExecutionRunEvent(payload.aries_run_id, payload.event_id)) {
        return {
          status: 'accepted',
          ariesRunId: payload.aries_run_id,
          duplicate: true,
        };
      }

      const correlationError = validateRunCorrelation(run, payload);
      if (correlationError) {
        return correlationError;
      }

      const approvalError = validateApprovalTransition(run, payload);
      if (approvalError) {
        return approvalError;
      }

      // The shared Hermes protocol emits `stopped`; Aries persists the canonical
      // cancellation state everywhere, including the marketing runtime that is
      // updated before the execution record below.
      const canonicalPayload: HermesRunCallbackPayload = payload.status === 'stopped'
        ? { ...payload, status: 'cancelled' }
        : payload;

      if (run.domain === 'marketing') {
        await applyHermesMarketingCallback(run, canonicalPayload);
      }

      let appliedStatus = executionStatus(canonicalPayload.status);
      let appliedError = canonicalPayload.error
        ? {
            code: canonicalPayload.error.code ?? 'hermes_callback_error',
            message: canonicalPayload.error.message,
            retryable: canonicalPayload.error.retryable,
          }
        : null;

      // Marketing callback application can fail closed after a nominally
      // completed/approval-required Hermes delivery (for example when every
      // reported video artifact falls outside approved cache roots). Persist
      // that application-level terminal outcome on the execution record too.
      if (run.domain === 'marketing' && run.marketing_job_id && appliedStatus !== 'cancelled') {
        const marketingDoc = await loadSocialContentJobRuntime(run.marketing_job_id).catch(() => null);
        if (marketingDoc?.state === 'failed') {
          appliedStatus = 'failed';
          appliedError = marketingDoc.last_error
            ? {
                code: marketingDoc.last_error.code,
                message: marketingDoc.last_error.message,
                retryable: marketingDoc.last_error.retryable,
              }
            : {
                code: 'marketing_callback_application_failed',
                message: 'Marketing callback application failed without a recorded error.',
                retryable: false,
              };
        }
      }

      if (appliedStatus === 'failed' && !appliedError) {
        appliedError = {
          code: 'hermes_run_failed',
          message: `Hermes reported a failed ${payload.stage ?? 'execution'} run without error details.`,
          retryable: false,
        };
      }

      markExecutionRunEventApplied(payload.aries_run_id, {
        eventId: payload.event_id,
        status: appliedStatus,
        stage: payload.stage,
        result: payload.output ?? (payload.approval ? sanitizeApprovalForRunRecord(payload.approval) : null),
        externalRunId: payload.hermes_run_id,
        error: appliedError,
        modelReported: payload.usage?.model ?? null,
        promptTokens: payload.usage?.prompt_tokens ?? null,
        completionTokens: payload.usage?.completion_tokens ?? null,
        totalTokens: payload.usage?.total_tokens ?? null,
        costCents: estimateAiCostCents(payload.usage?.total_tokens),
      });

      return {
        status: 'accepted',
        ariesRunId: payload.aries_run_id,
        duplicate: false,
      };
    });
  } catch (error) {
    if (error instanceof ExecutionRunLockError) {
      return { status: 'error', reason: 'execution_run_locked' };
    }
    throw error;
  }
}
