export const automationJobs = [
  {
    id: 'aries-private-repo-backup',
    name: 'Aries private repo backup',
    cron: '15 */6 * * *',
    tz: 'America/Los_Angeles',
    skill: 'aries-private-repo-backup',
    purpose: 'Stage current repo changes, commit them to a backup branch, and create or update a backup pull request on the configured private GitHub remote.',
  },
  {
    id: 'aries-overnight-self-improve',
    name: 'Aries overnight self-improvement',
    cron: '0 4 * * *',
    tz: 'America/Los_Angeles',
    skill: 'aries-overnight-self-improve',
    purpose: 'Pick one small additive nightly improvement, validate it, and log the shipped result to the nightly build log plus daily memory.',
    context: [
      '- Board: /home/node/.openclaw/projects/shared/team/execution-tasks.json',
      '- Feedback: data/feedback-processing-log.json',
      '- Build log: data/nightly-build-log.json',
      '- Design skill: skills/superdesign/SKILL.md',
      '- Build: npm run build',
      '- Runtime check: docker compose ps',
    ],
  },
  {
    id: 'aries-daily-brief',
    name: 'Aries daily brief',
    cron: '0 8 * * *',
    tz: 'America/Los_Angeles',
    skill: 'aries-daily-brief',
    purpose: 'Generate the morning priorities/overnight activity/pending actions brief.',
  },
  {
    id: 'aries-github-feedback-connector',
    name: 'Aries GitHub feedback connector',
    cron: '0 7 * * *',
    tz: 'America/Los_Angeles',
    skill: 'aries-github-feedback-connector',
    purpose: 'Sync GitHub issues, classify bug vs feature, route each pending item to the correct skill workflow, and update the processing log.',
  },
  {
    id: 'aries-github-feedback-daily-summary',
    name: 'Aries GitHub feedback daily summary',
    cron: '0 18 * * *',
    tz: 'America/Los_Angeles',
    skill: 'aries-github-feedback-daily-summary',
    purpose: 'Deliver the daily batch summary for non-critical GitHub feedback items that were processed and logged.',
  },
  {
    id: 'aries-system-reference-rollup',
    name: 'Aries rolling system reference',
    cron: '45 21 * * *',
    tz: 'America/Los_Angeles',
    skill: 'aries-rolling-system-reference',
    purpose: 'Update docs/SYSTEM-REFERENCE.md with architecture, inventory, cron jobs, and known issues.',
  },
  {
    id: 'aries-daily-standup',
    name: 'Aries daily standup',
    cron: '0 9 * * 1-5',
    tz: 'America/Los_Angeles',
    skill: 'aries-daily-standup',
    purpose: 'Generate a board-based daily standup transcript with per-lane chief reports, workspace verification, and blocker visibility.',
  },
  {
    id: 'aries-weekly-review',
    name: 'Aries weekly review',
    cron: '0 14 * * 5',
    tz: 'America/Los_Angeles',
    skill: 'aries-weekly-review',
    purpose: 'Generate the Friday weekly review from live board, git, cron, backlog, and service-health truth, save it under memory/reviews, and optionally email the HTML version.',
    context: [
      '- Board: /home/node/.openclaw/projects/shared/team/execution-tasks.json',
      '- Reviews: memory/reviews/',
      '- Email env: ARIES_WEEKLY_REVIEW_EMAIL + ARIES_WEEKLY_REVIEW_EMAIL_SCRIPT',
      '- Summary delivery: cron announce target',
    ],
  },
]
