export const automationJobs = [
  {
    id: 'aries-private-repo-backup',
    name: 'Aries private repo backup',
    cron: '15 */6 * * *',
    tz: 'America/Los_Angeles',
    skill: 'aries-private-repo-backup',
    purpose: 'Stage current repo changes, commit them to a backup branch, and create or update a backup pull request on the configured private GitHub remote.',
  },
  {
    id: 'aries-overnight-self-improve',
    name: 'Aries overnight self-improvement',
    cron: '0 4 * * *',
    tz: 'America/Los_Angeles',
    skill: 'aries-overnight-self-improve',
    purpose: 'Pick one small additive nightly improvement, validate it, and log the shipped result to the nightly build log plus daily memory.',
    context: [
      '- Board: /home/node/.openclaw/projects/shared/team/execution-tasks.json',
      '- Feedback: data/feedback-processing-log.json',
      '- Build log: data/nightly-build-log.json',
      '- Design skill: skills/superdesign/SKILL.md',
      '- Build: npm run build',
      '- Runtime check: docker compose ps',
    ],
  },
  {
    id: 'aries-daily-brief',
    name: 'Aries daily brief',
    cron: '0 8 * * *',
    tz: 'America/Los_Angeles',
    skill: 'aries-daily-brief',
    purpose: 'Generate the morning priorities/overnight activity/pending actions brief.',
  },
  {
    id: 'aries-daily-standup',
    name: 'Aries daily standup',
    cron: '30 8,13,17 * * 1-5',
    tz: 'America/Los_Angeles',
    skill: 'aries-daily-standup-orchestrator',
    purpose: 'Generate the board-derived Aries chief standup, write the transcript and per-chief reports to /home/node/.openclaw/projects/shared/teams, and announce the concise operational summary.',
  },
  {
    id: 'aries-standup-watchdog',
    name: 'Aries standup watchdog',
    cron: '50 8,13,17 * * 1-5',
    tz: 'America/Los_Angeles',
    skill: 'aries-standup-watchdog',
    purpose: 'Verify that the current standup transcript and per-chief reports exist in /home/node/.openclaw/projects/shared/teams and that no forbidden local standup artifacts were recreated.',
  },
  {
    id: 'aries-github-feedback-connector',
    name: 'Aries GitHub feedback connector',
    cron: '0 7 * * *',
    tz: 'America/Los_Angeles',
    message:
      'Work in /home/node/openclaw/aries-app. Run node scripts/automations/feedback-connector.mjs sync --json. For each pending bug, use the bug-triage skill. For each pending feature, use the feature-pipeline skill. Update data/feedback-processing-log.json after each item with node scripts/automations/feedback-connector.mjs mark --number <issue> --patch-json <json>. Return only: status, critical_alerts, bugs_processed, features_processed, batched_for_summary, errors.',
    purpose: 'Sync GitHub issues, classify bug vs feature, route each pending item to the correct skill workflow, and update the processing log.',
  },
  {
    id: 'aries-github-feedback-daily-summary',
    name: 'Aries GitHub feedback daily summary',
    cron: '0 18 * * *',
    tz: 'America/Los_Angeles',
    message:
      'Work in /home/node/openclaw/aries-app. Run node scripts/automations/feedback-daily-summary.mjs --mark-sent. Return only the emitted summary.',
    purpose: 'Deliver the daily batch summary for non-critical GitHub feedback items that were processed and logged.',
  },
  {
    id: 'aries-runtime-error-intake',
    name: 'Aries runtime error intake',
    cron: '5,35 * * * *',
    tz: 'America/Los_Angeles',
    message:
      'Read and follow: /home/node/openclaw/aries-app/skills/aries-runtime-error-intake/SKILL.md\n\nContext:\n- Project: /home/node/openclaw/aries-app\n- Incident log: /home/node/openclaw/aries-app/data/runtime-error-incidents.json\n- Delivery lane: Discord #ai-engineering with Telegram fallback handled by the cron delivery config.',
    purpose: 'Scan Aries runtime and automation health, normalize failures into the runtime incident log, and announce the concise detection/resolution summary.',
  },
  {
    id: 'aries-runtime-error-repair-loop',
    name: 'Aries runtime error repair loop',
    cron: '10,40 * * * *',
    tz: 'America/Los_Angeles',
    message:
      'Read and follow: /home/node/openclaw/aries-app/skills/aries-runtime-error-repair-loop/SKILL.md\n\nContext:\n- Project: /home/node/openclaw/aries-app\n- Incident log: /home/node/openclaw/aries-app/data/runtime-error-incidents.json\n- Delivery lane: Discord #ai-engineering with Telegram fallback handled by the cron delivery config.',
    purpose: 'Work the highest-priority repairable runtime incident with a bounded fix loop, validate the result, and announce the concise resolution or escalation summary.',
  },
  {
    id: 'aries-system-reference-rollup',
    name: 'Aries rolling system reference',
    cron: '45 21 * * *',
    tz: 'America/Los_Angeles',
    skill: 'aries-rolling-system-reference',
    purpose: 'Update docs/SYSTEM-REFERENCE.md with architecture, inventory, cron jobs, and known issues.',
  },
  {
    id: 'aries-daily-standup',
    name: 'Aries daily standup',
    cron: '0 9 * * 1-5',
    tz: 'America/Los_Angeles',
    skill: 'aries-daily-standup',
    purpose: 'Generate a board-based daily standup transcript with per-lane chief reports, workspace verification, and blocker visibility.',
  },
  {
    id: 'aries-weekly-review',
    name: 'Aries weekly review',
    cron: '0 14 * * 5',
    tz: 'America/Los_Angeles',
    skill: 'aries-weekly-review',
    purpose: 'Generate the Friday weekly review from live board, git, cron, backlog, and service-health truth, save it under memory/reviews, and optionally email the HTML version.',
    context: [
      '- Board: /home/node/.openclaw/projects/shared/team/execution-tasks.json',
      '- Reviews: memory/reviews/',
      '- Email env: ARIES_WEEKLY_REVIEW_EMAIL + ARIES_WEEKLY_REVIEW_EMAIL_SCRIPT',
      '- Summary delivery: cron announce target',
    ],
  },
]
