import assert from 'node:assert/strict';
import test from 'node:test';
import { handlePostCreativeMemoryContextPackPreview } from '../app/api/creative-memory/context-pack/preview/route';
import { handlePostCreativeMemoryOutcomeLabel } from '../app/api/creative-memory/outcome-labels/route';
import { handlePostCreativeMemoryPromptRecipePreview } from '../app/api/creative-memory/prompt-recipes/preview/route';
import { handlePostCreativeMemoryGeneratedAssets } from '../app/api/creative-memory/generated-assets/route';

const tenantLoader = async () => ({ userId:'1', tenantId:'1', tenantSlug:'demo', role:'tenant_admin' as const });
const brief = { objective:'lead magnet signups', platform:'instagram', placement:'feed', aspectRatio:'4:5', funnelStage:'TOFU', offer:'Checklist', audience:'ops managers', creativeType:'native educational image', cta:'Download', imageText:['A','B','C'] };
function req(body: unknown) { return new Request('http://test.local', { method:'POST', body: JSON.stringify(body), headers:{'content-type':'application/json'} }); }
function db() { return { query: async(sql:string)=>{ if(sql.includes('business_profiles')) return { rows:[{business_name:'Acme',brand_voice:'direct',style_vibe:'premium',offer:'Checklist'}] }; if(sql.includes('style_cards')) return { rows:[{id:'s1',status:'active',name:'Native educational',prompt_guidance:'Use a native note',negative_guidance:'No robots'}] }; if(sql.includes('creative_assets')) return { rows:[{id:'a1',source_type:'generated_by_aries',permission_scope:'generated',media_type:'image',storage_kind:'runtime_asset',served_asset_ref:'/api/marketing/jobs/j/assets/a',usable_for_generation:true,learning_lifecycle:'approved_for_generation'}] }; if(sql.includes('market_pattern_notes')) return { rows:[{id:'m1',source_label:'Competitor set',pattern:'Contrarian hooks'}] }; if(sql.startsWith('INSERT')) return { rows:[{id:'new-id'}] }; return { rows:[] }; } }; }

test('context-pack preview uses current tenant and returns safe shape', async () => { const res=await handlePostCreativeMemoryContextPackPreview(req({brief}), tenantLoader, db() as any); assert.equal(res.status,200); const json=await res.json(); assert.equal(json.status,'ok'); assert.equal(json.data.contextPack.selectedStyleCards.length,1); assert.equal(JSON.stringify(json).includes('tenantId'), false); assert.equal(JSON.stringify(json).includes('storageKey'), false); });
test('prompt preview is side-effect free and includes baseline comparison', async () => { const fake=db(); const res=await handlePostCreativeMemoryPromptRecipePreview(req({brief}), tenantLoader, fake as any); assert.equal(res.status,200); const json=await res.json(); assert.match(json.data.promptRecipe.baselinePrompt,/Objective/); assert.match(json.data.promptRecipe.compiledPrompt,/Memory-assisted guidance/); });
test('outcome labels require idempotency keys', async () => { const res=await handlePostCreativeMemoryOutcomeLabel(req({label:'approved'}), tenantLoader, db() as any); assert.equal(res.status,400); const json=await res.json(); assert.equal(json.status,'error'); });
test('outcome labels save manual learning events', async () => { const res=await handlePostCreativeMemoryOutcomeLabel(req({label:'used_in_campaign', idempotencyKey:'k1', promptRecipeId:'p1'}), tenantLoader, db() as any); assert.equal(res.status,201); const json=await res.json(); assert.equal(json.data.label.confidenceBasis,'manual_label'); });

test('generated assets route loads prompts from saved recipe provenance', async () => { const fake = { query: async (sql:string, values?:unknown[]) => { if(sql.includes('SELECT compiled_prompt')) return { rows:[{ compiled_prompt:'MEMORY SAVED PROMPT', context_pack:{ status:'ready', promptProvenance:{ baselinePrompt:'BASELINE SAVED PROMPT', canGenerate:true } } }] }; if(sql.startsWith('INSERT INTO generated_assets')) return { rows:[{ id: values?.[5] === 'baseline' ? 'g1' : 'g2', variant_kind: values?.[5], prompt_text: values?.[6], learning_lifecycle:'suggested', review_status:'pending', creative_asset_id:null }] }; return { rows:[] }; } }; const res = await handlePostCreativeMemoryGeneratedAssets(req({promptRecipeId:'p1', baselinePrompt:'CLIENT SHOULD NOT WIN', memoryPrompt:'CLIENT SHOULD NOT WIN'}), tenantLoader, fake as any); assert.equal(res.status,201); const json=await res.json(); assert.equal(json.data.generatedAssets.length,2); assert.equal(JSON.stringify(json).includes('CLIENT SHOULD NOT WIN'), false); });
