import assert from 'node:assert/strict';
import test from 'node:test';
import { createGeneratedAssetCandidate } from '../backend/creative-memory/generatedAssets';
import { saveCampaignLearningLabel } from '../backend/creative-memory/learningEvents';
test('generated assets start as pending learning candidates', async () => { const db={query:async(sql:string)=> sql.includes('SELECT compiled_prompt') ? ({rows:[{compiled_prompt:'MEMORY PROMPT', context_pack:{status:'ready', promptProvenance:{baselinePrompt:'BASELINE PROMPT', canGenerate:true}}}]}) : sql.includes('SELECT id, source_type') ? ({rows:[{id:'a1',source_type:'generated_by_aries',permission_scope:'generated'}]}) : ({rows:[{id:'g1', variant_kind:'baseline', prompt_text:'BASELINE PROMPT', learning_lifecycle:'suggested', review_status:'pending', creative_asset_id:'a1'}]})}; const g=await createGeneratedAssetCandidate({tenantId:'1'} as any, db as any, {promptRecipeId:'p1',creativeAssetId:'a1'}); assert.equal(g.learningLifecycle,'suggested'); assert.equal(g.reviewStatus,'pending'); });
test('labels are idempotency-keyed manual confidence signals', async () => { const db={query:async(sql:string, values:unknown[])=>({rows:[{id:'l1', values}]})}; const l=await saveCampaignLearningLabel({tenantId:'1'} as any, db as any, {idempotencyKey:'k1',label:'used_in_campaign',promptRecipeId:'p1'}); assert.equal(l.confidenceBasis,'manual_label'); assert.equal(l.performanceScored,false); });

test('labels reject orphan targets before writing', async () => { const db={query:async()=>{ throw new Error('should not write'); }}; await assert.rejects(() => saveCampaignLearningLabel({tenantId:'1'} as any, db as any, {idempotencyKey:'k1',label:'used_in_campaign'}), /reference a prompt recipe or generated asset/); });

test('label idempotency key cannot be replayed against a different target', async () => { let calls=0; const db={query:async()=>{ calls += 1; return calls === 1 ? {rows:[]} : {rows:[{id:'l1',label:'used_in_campaign',source:'operator',note:null,prompt_recipe_id:'old-recipe',generated_asset_id:null}]}; }}; await assert.rejects(() => saveCampaignLearningLabel({tenantId:'1'} as any, db as any, {idempotencyKey:'k1',label:'used_in_campaign',promptRecipeId:'new-recipe'}), /different outcome label or target/); });
