import assert from 'node:assert/strict';
import test from 'node:test';
import { retrieveCreativeContextPack } from '../backend/creative-memory/retrieval';
import { requireNumericTenantId } from '../backend/creative-memory/tenant';
const brief = { objective:'lead magnet signups', platform:'instagram', placement:'feed', aspectRatio:'4:5', funnelStage:'TOFU', offer:'Checklist', audience:'ops managers', creativeType:'native educational image', cta:'Download', imageText:['A','B'] };
function db(rows: Record<string, unknown>[][]) { let i=0; return { query: async()=>({ rows: rows[i++] ?? [] }) }; }
test('requires materialized numeric tenant ids', () => { assert.equal(requireNumericTenantId({tenantId:'7'} as any),7); assert.throws(()=>requireNumericTenantId({tenantId:'public_campaign'} as any), /database-backed/); });
test('retrieval excludes archived cards and competitor direct examples', async () => { const pack=await retrieveCreativeContextPack({tenantId:'1'} as any, db([[{business_name:'Acme'}],[{id:'arch',status:'archived'},{id:'style1',status:'active',name:'Native',prompt_guidance:'Use native',negative_guidance:'No robots'}],[{id:'c1',source_type:'competitor_meta_ad',permission_scope:'public_ad_library'},{id:'a1',source_type:'generated_by_aries',permission_scope:'generated',media_type:'image',storage_kind:'runtime_asset',served_asset_ref:'/api/marketing/jobs/j/assets/a',usable_for_generation:true,learning_lifecycle:'approved_for_generation'}],[{id:'m1',source_label:'Competitor set',pattern:'Short contrarian hooks'}]]) as any, brief as any); assert.equal(pack.selectedStyleCards.length,1); assert.equal(pack.selectedExamples.length,1); assert.equal(pack.marketPatternNotes.length,1); assert(pack.excludedCandidates.some(e=>e.reason==='style_card_archived')); assert(pack.excludedCandidates.some(e=>e.reason==='competitor_direct_example_forbidden')); });
test('retrieval returns insufficient memory fallback', async () => { const pack=await retrieveCreativeContextPack({tenantId:'1'} as any, db([[{}],[],[],[]]) as any, brief as any); assert.equal(pack.status,'insufficient_memory'); });
test('retrieval does not treat style-card-only memory as generation-ready', async () => { const pack=await retrieveCreativeContextPack({tenantId:'1'} as any, db([[{}],[{id:'style1',status:'active',name:'Native',prompt_guidance:'Use native'}],[],[]]) as any, brief as any); assert.equal(pack.status,'insufficient_memory'); assert.equal(pack.selectedStyleCards.length,1); assert.equal(pack.selectedExamples.length,0); });
