-- 20260814000000_drop_insights_llm_calls.sql
--
-- AA-129 item 12: drop the dead `insights_llm_calls` table.
--
-- The table was created as a per-LLM-call cost audit log ("every LLM call with
-- cost, tokens, and outcome") but has no application reader or writer. This
-- statement is mirrored in scripts/init-db.js, the production deploy path.
--
-- Its intended job is now done properly by `task_execution_log` (AA-159), which
-- records the processing engine, model hint, tokens, cost and duration for real
-- work, with the rollup/retention layer (AA-161) on top. Keeping a second cost
-- table invites someone to read the wrong one.
--
-- The ticket selected DROP. No production row-count assumption is required:
-- the live-Postgres regression test seeds a row, runs db:init, and verifies the
-- table is removed. `IF EXISTS` keeps this idempotent on a database that never
-- ran the original CREATE (the
-- table is `CREATE TABLE IF NOT EXISTS` in init-db, so its presence varies by
-- how old the deployment is). The index goes with the table automatically; it
-- is named here only so a reader grepping for the index finds this file.
--
-- Reversal, if ever needed, is the CREATE TABLE block removed from
-- scripts/init-db.js in the same commit — recoverable from git history.

DROP TABLE IF EXISTS insights_llm_calls;
-- (idx_insights_llm_calls_tenant_called_at is dropped with its table)
