/**
 * Minimal, zero-dependency Markdown -> HTML converter.
 *
 * Not CommonMark-complete. Handles the patterns we actually ship to the
 * approval viewer for brand bibles, website brand analysis, and similar
 * documents generated by the pipeline:
 *
 *   - ATX headings (# through ######)
 *   - Bold (**x** / __x__), italic (*x* / _x_), inline code (`x`)
 *   - Unordered lists (-, *, +) and ordered lists (1. / 2.)
 *   - Fenced code blocks (```lang ... ```)
 *   - Blockquotes (> ...)
 *   - Links ([label](url))
 *   - Paragraphs (blank-line separated)
 *
 * HTML-escapes everything before applying markdown rules, so rendered
 * output is safe to drop into a server-rendered page without dangerouslyXYZ
 * concerns on the source markdown itself. The caller still controls how
 * the resulting HTML is embedded.
 *
 * Prefer marked / remark / react-markdown if we end up needing tables,
 * GFM extensions, or tighter CommonMark compliance. This is deliberately
 * tiny so it can live in `lib/` without a new dependency.
 */
export function renderSimpleMarkdown(source: string): string {
  const escaped = escapeHtml(source);
  const lines = escaped.split(/\r?\n/);

  const out: string[] = [];
  let inCodeFence = false;
  let codeFenceLang = '';
  let codeFenceLines: string[] = [];
  let paragraphLines: string[] = [];
  let listStack: Array<'ul' | 'ol'> = [];

  const flushParagraph = () => {
    if (paragraphLines.length === 0) return;
    const text = paragraphLines.join(' ').trim();
    if (text) {
      out.push(`<p>${applyInline(text)}</p>`);
    }
    paragraphLines = [];
  };

  const flushList = () => {
    while (listStack.length > 0) {
      const tag = listStack.pop();
      out.push(`</${tag}>`);
    }
  };

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i];
    const line = rawLine.replace(/\s+$/, '');

    // Fenced code block marker
    const fenceMatch = /^```(\w*)\s*$/.exec(line);
    if (fenceMatch) {
      if (inCodeFence) {
        out.push(
          `<pre><code${codeFenceLang ? ` data-lang="${codeFenceLang}"` : ''}>${codeFenceLines.join('\n')}</code></pre>`,
        );
        inCodeFence = false;
        codeFenceLang = '';
        codeFenceLines = [];
      } else {
        flushParagraph();
        flushList();
        inCodeFence = true;
        codeFenceLang = fenceMatch[1] || '';
      }
      continue;
    }

    if (inCodeFence) {
      codeFenceLines.push(rawLine);
      continue;
    }

    // Blank line -> paragraph / list boundary
    if (line.trim() === '') {
      flushParagraph();
      flushList();
      continue;
    }

    // Headings
    const headingMatch = /^(#{1,6})\s+(.+)$/.exec(line);
    if (headingMatch) {
      flushParagraph();
      flushList();
      const level = headingMatch[1].length;
      out.push(`<h${level}>${applyInline(headingMatch[2].trim())}</h${level}>`);
      continue;
    }

    // Blockquote
    const bqMatch = /^&gt;\s?(.*)$/.exec(line);
    if (bqMatch) {
      flushParagraph();
      flushList();
      out.push(`<blockquote>${applyInline(bqMatch[1])}</blockquote>`);
      continue;
    }

    // Horizontal rule
    if (/^(?:-\s*){3,}$|^(?:\*\s*){3,}$|^(?:_\s*){3,}$/.test(line.trim())) {
      flushParagraph();
      flushList();
      out.push('<hr />');
      continue;
    }

    // Ordered list item (1. text)
    const orderedMatch = /^(\s*)(\d+)\.\s+(.+)$/.exec(line);
    if (orderedMatch) {
      flushParagraph();
      if (listStack[listStack.length - 1] !== 'ol') {
        flushList();
        out.push('<ol>');
        listStack.push('ol');
      }
      out.push(`<li>${applyInline(orderedMatch[3])}</li>`);
      continue;
    }

    // Unordered list item (- or * or +)
    const unorderedMatch = /^(\s*)[-*+]\s+(.+)$/.exec(line);
    if (unorderedMatch) {
      flushParagraph();
      if (listStack[listStack.length - 1] !== 'ul') {
        flushList();
        out.push('<ul>');
        listStack.push('ul');
      }
      out.push(`<li>${applyInline(unorderedMatch[2])}</li>`);
      continue;
    }

    // Regular paragraph line
    flushList();
    paragraphLines.push(line);
  }

  if (inCodeFence) {
    out.push(`<pre><code>${codeFenceLines.join('\n')}</code></pre>`);
  }
  flushParagraph();
  flushList();

  return out.join('\n');
}

function escapeHtml(input: string): string {
  return input
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function applyInline(text: string): string {
  let out = text;

  // Inline code first so other rules don't touch its content
  out = out.replace(/`([^`]+)`/g, (_match, code) => `<code>${code}</code>`);

  // Links: [label](url) — url is already HTML-escaped, reject javascript: schemes
  out = out.replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_match, label, url) => {
    const trimmed = url.trim();
    const lower = trimmed.toLowerCase();
    if (lower.startsWith('javascript:') || lower.startsWith('data:') || lower.startsWith('vbscript:')) {
      return `<span>${label}</span>`;
    }
    return `<a href="${trimmed}" target="_blank" rel="noopener noreferrer">${label}</a>`;
  });

  // Bold: **text** or __text__
  out = out.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
  out = out.replace(/__([^_]+)__/g, '<strong>$1</strong>');

  // Italic: *text* or _text_  — skip when adjacent to word chars to avoid
  // breaking things like snake_case_identifiers
  out = out.replace(/(^|[^\w*])\*(?!\s)([^*]+)\*(?!\w)/g, '$1<em>$2</em>');
  out = out.replace(/(^|[^\w_])_(?!\s)([^_]+)_(?!\w)/g, '$1<em>$2</em>');

  return out;
}
