'use client';

import { Fragment, type ReactNode } from 'react';
import Image from 'next/image';

// T22: Per-platform preview UI primitives. Components in this folder render
// faithful platform-style previews; they consume image URLs that are already
// framed/generated by Hermes (T13) and aspect ratios resolved by T9.

export type PostPreviewPlatform = 'instagram' | 'facebook';

export type PostPreviewType = 'single' | 'carousel' | 'link_card';

export type PostPreviewAspectRatio = '4:5' | '1:1' | '1.91:1';

export interface PostPreviewMedia {
  url: string;
  alt: string;
}

export interface PostPreviewAuthor {
  name: string;
  handle?: string;
  avatarUrl?: string;
  timestampLabel?: string;
}

const ASPECT_TO_CLASS: Record<PostPreviewAspectRatio, string> = {
  '4:5': 'aspect-[4/5]',
  '1:1': 'aspect-square',
  '1.91:1': 'aspect-[1.91/1]',
};

const ASPECT_TO_RATIO: Record<PostPreviewAspectRatio, number> = {
  '4:5': 4 / 5,
  '1:1': 1,
  '1.91:1': 1.91,
};

export function aspectClass(ratio: PostPreviewAspectRatio): string {
  return ASPECT_TO_CLASS[ratio];
}

export function aspectNumeric(ratio: PostPreviewAspectRatio): number {
  return ASPECT_TO_RATIO[ratio];
}

export const INSTAGRAM_CAPTION_TRUNCATE_AT = 125;
export const FACEBOOK_CAPTION_TRUNCATE_AT = 480;
export const INSTAGRAM_MORE_LABEL = '...more';
export const FACEBOOK_MORE_LABEL = '...See more';

export interface CaptionTruncation {
  visible: string;
  fullText: string;
  isTruncated: boolean;
  moreLabel: string;
  limit: number;
}

export function truncateCaption(
  rawText: string,
  limit: number,
  moreLabel: string,
): CaptionTruncation {
  const fullText = typeof rawText === 'string' ? rawText : '';
  if (fullText.length <= limit) {
    return { visible: fullText, fullText, isTruncated: false, moreLabel, limit };
  }
  const sliced = fullText.slice(0, limit);
  // Prefer truncating at a space boundary if it lands within the last 20% of
  // the limit so the "...more" label doesn't break a word in half.
  const lastSpace = sliced.lastIndexOf(' ');
  const breakPoint = lastSpace > Math.floor(limit * 0.8) ? lastSpace : limit;
  const visible = fullText.slice(0, breakPoint).replace(/\s+$/, '');
  return { visible, fullText, isTruncated: true, moreLabel, limit };
}

const HASHTAG_PATTERN = /(#[A-Za-z0-9_]+)/g;
const HASHTAG_MATCH = /^#[A-Za-z0-9_]+$/;

export function captionWithHashtags(text: string): ReactNode[] {
  const segments = text.split(HASHTAG_PATTERN);
  const nodes: ReactNode[] = [];
  for (let i = 0; i < segments.length; i += 1) {
    const part = segments[i];
    if (!part) continue;
    if (HASHTAG_MATCH.test(part)) {
      nodes.push(
        <span
          key={`tag-${i}`}
          data-role="post-hashtag"
          data-hashtag={part.slice(1)}
          className="text-blue-500 no-underline"
        >
          {part}
        </span>,
      );
    } else {
      nodes.push(<Fragment key={`txt-${i}`}>{part}</Fragment>);
    }
  }
  return nodes;
}

export interface CaptionRendererProps {
  text: string;
  truncation: CaptionTruncation;
  authorName?: string;
}

export function CaptionRenderer(props: CaptionRendererProps) {
  const { truncation, authorName } = props;
  return (
    <p
      data-role="post-caption"
      data-truncated={truncation.isTruncated ? 'true' : 'false'}
      data-caption-limit={truncation.limit}
      data-caption-more-label={truncation.moreLabel}
      data-full-caption={truncation.fullText}
      className="whitespace-pre-wrap break-words text-sm leading-snug text-white"
    >
      {authorName ? (
        <span data-role="post-caption-author" className="mr-1 font-semibold">
          {authorName}
        </span>
      ) : null}
      <span data-role="post-caption-visible">
        {captionWithHashtags(truncation.visible)}
      </span>
      {truncation.isTruncated ? (
        <span
          data-role="post-caption-more"
          className="ml-1 cursor-pointer text-white/55"
        >
          {truncation.moreLabel}
        </span>
      ) : null}
    </p>
  );
}

export interface PreviewImageProps {
  media: PostPreviewMedia;
  aspectRatio: PostPreviewAspectRatio;
  imageRole?: string;
  priority?: boolean;
  sizes?: string;
}

// Wraps next/image with `fill` because preview consumers do not always know
// the source dimensions (Hermes-generated URLs do not carry width/height in
// the runtime doc). The aspect-ratio frame guarantees a stable layout box.
export function PreviewImage(props: PreviewImageProps) {
  const role = props.imageRole ?? 'post-image';
  const sizes = props.sizes ?? '(min-width: 640px) 480px, 100vw';
  return (
    <div
      data-role={role}
      data-aspect-ratio={props.aspectRatio}
      className={`relative w-full overflow-hidden bg-black/40 ${aspectClass(props.aspectRatio)}`}
    >
      <Image
        src={props.media.url}
        alt={props.media.alt}
        fill
        sizes={sizes}
        className="object-cover"
        priority={props.priority}
        unoptimized
      />
    </div>
  );
}

export interface PostHeaderProps {
  platform: PostPreviewPlatform;
  author: PostPreviewAuthor;
}

export function PostHeader(props: PostHeaderProps) {
  const initial = props.author.name?.trim().slice(0, 1).toUpperCase() || 'A';
  return (
    <div
      data-role="post-header"
      data-platform={props.platform}
      className="flex items-center gap-3 px-4 py-3"
    >
      <div
        data-role="post-avatar"
        aria-hidden="true"
        className="flex h-9 w-9 items-center justify-center rounded-full bg-gradient-to-br from-fuchsia-500 via-rose-500 to-amber-400 text-sm font-semibold text-white"
      >
        {initial}
      </div>
      <div className="flex flex-col leading-tight">
        <span data-role="post-author-name" className="text-sm font-semibold text-white">
          {props.author.name}
        </span>
        {props.author.handle ? (
          <span data-role="post-author-handle" className="text-xs text-white/55">
            {props.author.handle}
          </span>
        ) : null}
        {props.author.timestampLabel ? (
          <span data-role="post-timestamp" className="text-xs text-white/45">
            {props.author.timestampLabel}
          </span>
        ) : null}
      </div>
    </div>
  );
}

export interface PostFrameProps {
  platform: PostPreviewPlatform;
  postType: PostPreviewType;
  aspectRatio: PostPreviewAspectRatio;
  testId: string;
  children: ReactNode;
}

export function PostFrame(props: PostFrameProps) {
  return (
    <article
      data-role="post-preview"
      data-platform={props.platform}
      data-post-type={props.postType}
      data-aspect-ratio={props.aspectRatio}
      data-testid={props.testId}
      className="mx-auto w-full max-w-md overflow-hidden rounded-[1.25rem] border border-white/10 bg-[#0c0f12] text-white shadow-[0_24px_72px_rgba(0,0,0,0.45)]"
    >
      {props.children}
    </article>
  );
}
