import { addPolicy, addSnapshot, addChange, getLatestSnapshot } from './db.mjs';
import { hashContent, detectRiskFlags, generateMockAiSummary } from './scraper.mjs';
import { createDiff } from './differ.mjs';

const demoData = [
  {
    name: 'OpenAI Terms of Use',
    url: 'https://openai.com/policies/terms-of-use',
    v1: `Terms of Use
Effective Date: January 15, 2026

1. Eligibility
You must be at least 13 years old to use our services. If you are under 18, you must have parental consent.

2. Account Registration
You must provide accurate information when creating an account. You are responsible for maintaining the security of your account credentials.

3. Acceptable Use
You may not use our services to generate content that is illegal, harmful, or deceptive. You may not attempt to reverse engineer our models.

4. Content Ownership
You retain ownership of your input content. Output generated by our models is owned by you, subject to these terms.

5. Data Usage
We may use anonymized usage data to improve our services. We do not use your input or output content to train our models without your explicit consent.

6. Liability
Our total liability is limited to the amount you paid us in the 12 months preceding the claim. We are not liable for indirect, incidental, or consequential damages.

7. Cancellation
You may cancel your subscription at any time. Refunds are available within 30 days of payment. Upon cancellation, your data will be deleted within 90 days.

8. Modifications
We may modify these terms at any time. We will provide 30 days notice of material changes via email.`,

    v2: `Terms of Use
Effective Date: April 1, 2026

1. Eligibility
You must be at least 18 years old to use our services.

2. Account Registration
You must provide accurate information when creating an account. You are responsible for maintaining the security of your account credentials. We may verify your identity using third-party services.

3. Acceptable Use
You may not use our services to generate content that is illegal, harmful, deceptive, or that infringes on third-party rights. You may not attempt to reverse engineer our models or use outputs to train competing AI systems.

4. Content Ownership
You retain ownership of your input content. Output generated by our models is licensed to you for commercial and non-commercial use, subject to these terms and our usage policies.

5. Data Usage
We may use your input and output content to train, improve, and develop our AI models and related services. You may opt out of training data usage through your account settings. Anonymized and aggregated data may be used without restriction.

6. Liability
Our total liability is limited to the amount you paid us in the 3 months preceding the claim. We are not liable for indirect, incidental, or consequential damages. All disputes are subject to binding arbitration in San Francisco, CA.

7. Cancellation
You may cancel your subscription with 30 days written notice. No refunds are available after the first 14 days. Auto-renewal applies to all subscription plans. Upon cancellation, your data will be retained for 24 months for compliance purposes.

8. Modifications
We may modify these terms at any time. Material changes take effect 14 days after posting to our website.`
  },
  {
    name: 'Stripe Services Agreement',
    url: 'https://stripe.com/legal/ssa',
    v1: `Stripe Services Agreement
Last Updated: February 1, 2026

1. Services
Stripe provides payment processing services for businesses. We process transactions on your behalf and settle funds to your designated bank account.

2. Fees
Transaction fees are 2.9% + $0.30 per successful charge. Volume discounts are available for businesses processing over $100,000/month.

3. Data Handling
We process payment data in compliance with PCI DSS Level 1. Customer payment information is encrypted and stored securely. We do not share payment data with third parties except as required to process transactions.

4. Disputes
You are responsible for managing customer disputes. Stripe charges a $15 dispute fee for each chargeback. We provide dispute management tools at no additional cost.

5. Account Termination
Either party may terminate with 30 days notice. Upon termination, we will process remaining settlements within 90 business days.`,

    v2: `Stripe Services Agreement
Last Updated: March 15, 2026

1. Services
Stripe provides payment processing services and financial technology infrastructure for businesses. We process transactions on your behalf and settle funds to your designated bank account.

2. Fees
Transaction fees are 2.9% + $0.30 per successful charge for standard accounts. A platform fee of 0.5% applies to Stripe Connect transactions. Volume discounts are available for businesses processing over $250,000/month. Fees are subject to annual adjustment with 60 days notice.

3. Data Handling
We process payment data in compliance with PCI DSS Level 1. Customer payment information is encrypted and stored securely. We may share transaction metadata with our fraud detection partners and financial institution partners. We may use aggregated transaction patterns to improve our risk models and machine learning systems.

4. Disputes
You are responsible for managing customer disputes. Stripe charges a $25 dispute fee for each chargeback. We provide dispute management tools at no additional cost.

5. Account Termination
Either party may terminate with 30 days notice. Upon termination, we will process remaining settlements within 120 business days. A 1% early termination fee applies to accounts less than 12 months old.`
  },
  {
    name: 'Vercel Privacy Policy',
    url: 'https://vercel.com/legal/privacy-policy',
    v1: `Privacy Policy
Effective: January 2026

We collect information you provide directly, including name, email, and billing information. We also collect usage data such as deployment logs, build times, and feature usage.

We use your data to provide and improve our services, communicate with you, and ensure security. We do not sell your personal data.

We share data with service providers who help us operate our platform, including hosting providers, payment processors, and analytics services.

You may access, correct, or delete your personal data by contacting support@vercel.com. We respond to data requests within 30 days.`,

    v2: null
  }
];

console.log('Seeding demo data...');

for (const item of demoData) {
  const result = addPolicy(item.name, item.url);
  const policyId = result.lastInsertRowid;

  const hash1 = hashContent(item.v1);
  addSnapshot(policyId, item.v1, hash1);

  if (item.v2) {
    const hash2 = hashContent(item.v2);
    const snapResult = addSnapshot(policyId, item.v2, hash2);

    const diff = createDiff(item.v1, item.v2);
    const riskFlags = detectRiskFlags(diff);
    const aiSummary = generateMockAiSummary(diff, riskFlags);
    addChange(policyId, policyId + 100, snapResult.lastInsertRowid, diff, aiSummary, riskFlags);

    console.log(`  ${item.name}: change detected, flags: ${riskFlags.map(f => f.label).join(', ')}`);
  } else {
    console.log(`  ${item.name}: baseline snapshot only`);
  }
}

console.log('Demo data seeded. Run: node server.mjs');
