import { readFile, realpath } from 'node:fs/promises';
import path from 'node:path';

import { resolveDataRoot } from '@/lib/runtime-paths';
import { generatedAssetCandidates, marketingAssetRoots, stageCacheRoot } from './artifact-store';

const INGEST_SUBDIR = 'ingested-assets';

export type ReadMarketingAssetOptions = {
  tenantId?: string;
};

/**
 * Returns the set of subtrees whose first segment under the root is the
 * owning tenantId. Two families are currently tenant-scoped on disk:
 *
 *   1. `DATA_ROOT/ingested-assets/<tenantId>/...`  (user-uploaded media)
 *   2. `<stageCacheRoot>/<tenantId>/<runId>/...`   (per-stage cache)
 *
 * Paths outside these subtrees are not tenant-scoped (workflow specs, repo
 * source, raw pipeline output logs) and must NOT be rejected here — that
 * would block legitimate reads.
 */
function tenantScopedRootCandidates(): string[] {
  return [
    path.join(path.normalize(resolveDataRoot()), INGEST_SUBDIR),
    path.normalize(stageCacheRoot(1)),
    path.normalize(stageCacheRoot(2)),
    path.normalize(stageCacheRoot(3)),
    path.normalize(stageCacheRoot(4)),
  ];
}

/**
 * Resolve each tenant-scoped root to its realpath when possible so the
 * tenant-prefix check below operates in the same coordinate system as the
 * resolved candidate. Without this, a symlinked DATA_ROOT or
 * LOBSTER_STAGE*_CACHE_DIR makes `path.relative(normalizedRoot, realpathCandidate)`
 * start with `..` and the check silently skips that subtree, leaving a
 * false-negative on the cross-tenant boundary.
 *
 * Roots that do not exist on disk yet (fresh deploy, no cache populated)
 * fall back to the normalized path — realpath of a missing dir throws, and
 * a non-existent root can't host a cross-tenant read anyway.
 */
async function resolvedTenantScopedRoots(): Promise<string[]> {
  return Promise.all(
    tenantScopedRootCandidates().map((root) =>
      realpath(root).catch(() => root),
    ),
  );
}

async function tenantPrefixViolates(
  candidate: string,
  tenantId: string | undefined,
): Promise<boolean> {
  if (tenantId === undefined) {
    return false;
  }
  const tenantRoots = await resolvedTenantScopedRoots();
  for (const tenantRoot of tenantRoots) {
    const rel = path.relative(tenantRoot, candidate);
    if (rel === '' || rel.startsWith('..') || path.isAbsolute(rel)) {
      continue;
    }
    const segments = rel.split(path.sep).filter(Boolean);
    if (segments.length === 0) {
      continue;
    }
    if (segments[0] !== tenantId) {
      return true;
    }
  }
  return false;
}

/**
 * Safe reader for files referenced by the marketing runtime documents.
 *
 * Every path that lands on disk through the marketing pipeline eventually
 * needs to be read back out (API handler serving raw bytes, materials
 * viewer rendering markdown, preview endpoints). We centralize the read
 * so both callers get the same guarantees:
 *
 *   1. `normalizeAssetPath` strips any `.` / `..` segments so relative
 *      paths cannot climb out of the trusted root set they'll be joined
 *      against.
 *   2. `trustedRoots` is the closed set of directories we're willing to
 *      serve files from — DATA_ROOT (runtime artifacts), CODE_ROOT (repo
 *      source), artifact CWD/stage caches (generated pipeline outputs).
 *   3. `isWithinRoot` both before and after `realpath` resolution ensures
 *      symlink traversal doesn't escape the trusted root (an attacker who
 *      could plant a symlink inside the root still can't use it to read
 *      an arbitrary file outside it).
 *   4. `absoluteCompatibilityCandidates` handles the legacy `/app/aries-app`
 *      → `/app` path rewrite without widening the trust boundary.
 *
 * Returns the file contents as a Buffer when the path was safe and the
 * file existed, otherwise `null`. Throws on unexpected I/O errors so the
 * caller can decide whether to bubble up a 500.
 *
 * Runtime asset paths originate server-side (generated by the pipeline
 * or written by the onboarding/upload flows), but since those same flows
 * can be influenced by tenant input we treat them as untrusted and funnel
 * every read through this helper instead of calling `readFile` directly.
 */
export async function readMarketingAssetWithinAllowedRoots(
  filePath: string,
  options: ReadMarketingAssetOptions = {},
): Promise<Buffer | null> {
  const normalizedPath = normalizeAssetPath(filePath);
  if (!normalizedPath) {
    return null;
  }

  const roots = trustedRoots();
  const candidates =
    normalizedPath.kind === 'absolute'
      ? absoluteCompatibilityCandidates(normalizedPath.path)
      : roots.map((root) => path.resolve(root, normalizedPath.path));

  for (const candidate of candidates) {
    for (const root of roots) {
      if (!isWithinRoot(root, candidate)) {
        continue;
      }
      try {
        const [resolvedRoot, resolvedCandidate] = await Promise.all([
          realpath(root).catch(() => root),
          realpath(candidate),
        ]);
        if (!isWithinRoot(resolvedRoot, resolvedCandidate)) {
          continue;
        }
        // When the resolved candidate lives under DATA_ROOT/ingested-assets,
        // the first path segment is the owning tenant. A read scoped to a
        // different tenantId (or an empty one) must be denied even if the
        // path is otherwise within trusted roots — that's the cross-tenant
        // boundary this helper enforces.
        if (await tenantPrefixViolates(resolvedCandidate, options.tenantId)) {
          continue;
        }
        return await readFile(resolvedCandidate);
      } catch (error) {
        if (
          error &&
          typeof error === 'object' &&
          'code' in error &&
          (error.code === 'ENOENT' || error.code === 'ENOTDIR')
        ) {
          continue;
        }
        throw error;
      }
    }
  }

  return null;
}

type NormalizedAssetPath =
  | { kind: 'relative'; path: string }
  | { kind: 'absolute'; path: string };

function normalizeAssetPath(filePath: string): NormalizedAssetPath | null {
  const trimmed = filePath.trim();
  if (!trimmed) {
    return null;
  }

  if (path.isAbsolute(trimmed)) {
    return {
      kind: 'absolute',
      path: path.normalize(trimmed),
    };
  }

  const segments = trimmed.split(/[\\/]+/).filter(Boolean);
  if (segments.length === 0 || segments.some((segment) => segment === '.' || segment === '..')) {
    return null;
  }

  return {
    kind: 'relative',
    path: path.join(...segments),
  };
}

function trustedRoots(): string[] {
  return marketingAssetRoots();
}

function absoluteCompatibilityCandidates(filePath: string): string[] {
  return generatedAssetCandidates(filePath);
}

/**
 * Returns true only when the resolved candidate stays within the provided
 * root directory. Paths that escape upward or resolve to another absolute
 * location are rejected.
 */
function isWithinRoot(root: string, candidate: string): boolean {
  const relative = path.relative(root, candidate);
  return relative === '' || (!relative.startsWith('..') && !path.isAbsolute(relative));
}
